files: "^(systems/|tests/|.)"
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.6.3
    hooks:
      - id: isort
        name: isort (python)
      # - id: isort
      #   name: isort (cython)
      #   types: [cython]
      # - id: isort
      #   name: isort (pyi)
      #   types: [pyi]

  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.30.0
    hooks:
      - id: yapf
        args: [--parallel, --in-place]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8

  - repo: https://github.com/pycqa/pydocstyle
    rev: 5.1.1 
    hooks:
      - id: pydocstyle
        args: [--convention, google, --add-ignore, 'D1,D417']

  - repo: local
    hooks:
      - id: export-requirements
        name: Export requirements.txt
        language: system
        pass_filenames: false
        entry: .githooks/poetry_requirements.sh
        files: ^(pyproject.toml|poetry.lock)$
