repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/isort
    rev: 5.6.3
    hooks:
      - id: isort
        name: isort (python)
      - id: isort
        name: isort (cython)
        types: [cython]
      - id: isort
        name: isort (pyi)
        types: [pyi]

  - repo: local
    hooks:
      - id: export-requirements
        name: Export requirements.txt
        language: system
        pass_filenames: false
        entry: .githooks/poetry_requirements.sh
        files: ^(pyproject.toml|poetry.lock)$
        verbose: true
