[tool.poetry]
name = "systems"
version = "0.1.0"
description = "Systems code for Relectric car team."
authors = ["Relectric"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
pyzmq = "^22.0.3"
pyserial = "^3.5"
websockets = "^8.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
