on:
  push:
    branches:
      - main

jobs:
  build_docs:
    runs-on: ubuntu-latest
    name: Builds documentation and publishes to GitHub Pages
    steps:
      # Checkout repo
      - uses: actions/checkout@v1

      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"

      - name: Commit documentation changes
        run: |
          git clone https://github.com/relectric-car-team/systems.git --branch gh-pages --single-branch gh-pages
          cp -r docs/_build/html/* gh-pages/
          cd gh-pages
          git config --local user.email "27856297+dependabot-preview[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "docs: Update documentation :memo:" -a || true
          # The above command will fail if no changes were present, so we ignore
          # the return code.

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
