on:
  push:
    branches:
      - master

jobs:
  build_docs:
    runs-on: ubuntu-latest
    name: Builds documentation and publishes to GitHub Pages
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Python 3.9.1
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.2
        with:
          virtualenvs-create: true
          virtualenvs-in-project: false

      - name: Cache Poetry env
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-root

      - name: Install library
        run: poetry install

      - name: Build docs
        run: |
          poetry run sphinx-build -b html ./docs/source docs_build

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs_build
